# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0003_todo_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='check',
        ),
    ]
