# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0004_remove_todo_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
